---
title: "Project Checkpoint 2"
author: "Natalie Cartwright"
format: html
---

## Checkpoint 2

### Reasearch question: Which method of finding measles cases finds the most measeles cases? 


### Loading in the data sets
```{r}
library(tidyverse)

cases_month <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-06-24/cases_month.csv')
cases_year <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-06-24/cases_year.csv')


```



### Finding the summary statistics using iteration

```{r}
prop <- numeric(nrow(cases_year))
max <- nrow(cases_year)

for (i in 1:nrow(cases_year)) {
  lab <- cases_year$measles_lab_confirmed[i]
  epi <- cases_year$measles_epi_linked[i]
  clinic <- cases_year$measles_clinical[i]
  tot <- cases_year$measles_total[i]
  
  if (lab >= epi & lab >= clinic){
    prop[i] = lab / tot
    max[i] = "lab"
  } else if (epi >= lab & epi >= clinic) {
    prop[i] = epi / tot
    max[i] = "epi"
  } else {
    prop[i] = clinic / tot
    max[i] = "clinic"
  }
  
  prop[is.nan(prop)] <- 0
}


prop_tbl <- tibble(proportion = prop, method = max)

sum_prop <- prop_tbl |> 
  filter(prop != 0) |> 
  group_by(method)|> 
  summarise(count = n())

```


### Conclusion

According to my summary table, the method of confirming
measles cases by the lab results in finding the most measles
cases. 


